name: Super WorkFlow
on: [push]
jobs:
  wersja-docker-python:
    runs-on: ubuntu-latest
    steps:
      - run: python --version
      - run: docker -v
      - run: pip install docker
      - run: pip install pylint
  pylint-tester:
    runs-on: ubuntu-latest
    steps:    
      - run: find . -name '*.py' -exec pylint {} \;
      - run: pylint app.py
  uruchom-docker:
    runs-on: ubuntu-latest
    steps:
      - run: docker build --tag test-flask-app .
      - run: docker run -d -p 5000:5000 test-flask-app 